### PR TITLE
Update for Parameter Framework Audio base HAL.

### PR DESCRIPTION
**Pull request by sguiriec**
@plbossart, @cc6565 Please review this pull request. It is the update of the topic/nuc but without the switch to Parameter Framework base Audio HAL. The goal is to put the reference file for the Intel NuC under the public tree. topic/nuc is the reference branch with all the setting to the full switch.

@kalyankondapally just for your reference

Please note that with reference Audio configuration files have been fully tested with Music playback and switch between HDMI, headset and A2DP.

This patch is adding the reference configuration files in order to
support the Audio Parameter Framework base HAL for Intel NuC. Please note
that the configuration is still on baseline audio HAL. After swith to
Parameter Framework baseline HAL only run of mixin-update script will
be needed.

Jira:None

Test: Validated under Intel NuC 6i5SYH.

Signed-off-by: Sebastien Guiriec <sebastien.guiriec@intel.com>

### CODE REVIEW

**Comment by plbossart** [comment]
I am fine with merging but this seems to conflict with Francois Route Manager PFW removal, all the config files will have to be reworked. Seems more efficient to me to merge Francois' patches first and then update the HAL (less merges to do)?

**Comment by plbossart** [comment]
Actually I am lost, the patch seems to use the new definitions 

+                <mixPort name="primary_output" role="source" flags="AUDIO_OUTPUT_FLAG_PRIMARY"
 +                         card="PCH" device="0"
 +                         requirePreEnable="0" requirePostDisable="0" silencePrologMs="0"
 +                         periodSize="240" periodCount="2"
 +                         startThreshold="239" stopThreshold="480" silenceThreshold="0" availMin="240">

but it still has text files for criteria. What I am missing and what do I merge first?

**Comment by sguiriec** [comment]
We still have the option to use .txt file for the generation of the setting files. Just need to see with Francois if we can also try to make Parameter Framework release with XML format.

XML is just an improvement to avoid duplication or mismatch but not mandatory.
So you do not miss any stuff here.

For sure we can wait but I want to close on this to have less patch to cherry-pick for other people.

**Comment by cc6565** [comment]
I reworked the python script and android makefile to be able to use XML criteria / criterion types in order to be able to remove txt dup files. These files are NOT located in the PFW github but in HAL github and already merge. So, green light to swtich !

**Pull request merged**
