### PR TITLE
add sepolicy for KBL NUC

### PR DESCRIPTION
**Pull request by ceiba1985**
Change-Id: Ia35e39c95aa0eebf8e1b4445027efd2d98fda158
Signed-off-by: ji, zhenlong z <zhenlong.z.ji@intel.com>

### CODE REVIEW

**Comment by android-ia-srv** [comment]
Commit message is invalid for commit id:  https://github.com/android-ia/device-androidia/pull/120/commits/1a8c3772163d02e85a7596d817295edaa4da8a73 <br>Commit message should be as below: <br><br>Jira: Link to Jira [Default:None.]<br>Test: What tests are expected to pass <br>Signed-off-by: <Author/Contributor><br><br>For more details please refer to below wiki link: https://github.com/android-ia/manifest/wiki/Contributions

**Comment by sgnanase** [comment]
@ceiba1985 ,
Please make the init.rc change in mixins

**Comment by ceiba1985** [comment]
@sgnanase Done

**Comment by sgnanase** [comment]
Verified & Merged !!

**Pull request merged**
