### PR TITLE
kernel_64_defconfig: add CONFIG_SWITCH support

### PR DESCRIPTION
**Pull request by libinyang**
Add CONFIG_SWITCH=y in default config

Signed-off-by: Libin Yang <libin.yang@intel.com>

### CODE REVIEW

**Comment by kalyankondapally** [comment]
Can you fix commit message https://github.com/android-ia/manifest/wiki/Contributions#commit-template

**Comment by libinyang** [comment]
Summary of the patch:
This is a patch of enable hdmi_switch in kernel config.

Description of the fix.
The patches enable CONFIG_SWITCH, which will work with the below 3 patches to enable hdmi_switch:
aia: port switch class support  …			d24bc52
ALSA: hda - hdmi audio add support of switch  …			5cc8dea
config: enable CONFIG_SWITCH  …

Jira: (Link to Jira)
None

Test: (What tests are expected to pass).
With other 3 patches, it will enable hdmi_switch. There is "hdmi_state" node created in /sys/class/switch/pcixxxx/xxxx/  #xxxx is the pci id.

Signed-off-by:
Libin Yang <libin.yang@intel.com>

**Comment by kalyankondapally** [comment]
@plbossart Looks good for u ?

**Comment by kalyankondapally** [comment]
Closing this based on comment in kernel repo pull request that u are working on another solution.

**Pull request closed without merging**
