### PR TITLE
Add bootloader-control option in mixin.spec

### PR DESCRIPTION
**Pull request by xiaopingx**
add bootloader-control option to support
adb reboot bootloader
adb reboot-bootloader
adb reboot fastboot
adb reboot recovery

Bug ID: https://01.org/jira/browse/AIA-159
Test: I test it on Joule

Signed-off-by: hu,xiaopingx <xiaopingx.hu@intel.com>
Signed-off-by: Chen,Xihua <xihua.chen@intel.com>

### CODE REVIEW

**Comment by xiaopingx** [comment]
adb reboot bootloader
adb reboot-bootloader
adb reboot fastboot
adb reboot recovery
could work well Joule

**Comment by kalyankondapally** [comment]
@shobhitka ping

**Comment by kalyankondapally** [comment]
@Kishore409 Can you test on joule

**Comment by shobhitka** [comment]
@xiaopingx , can you put list of all pull request related to this pull request here so that its easy to review all of them in a unified context. I think there are multiple repos that are modified.

I think it would be a good practice to list all related pull requests in one of the main enabling pull request.

**Comment by xiaopingx** [comment]
https://github.com/android-ia/device-intel-common/pull/2
https://github.com/android-ia/system-core/pull/3
https://github.com/android-ia/bootable-recovery/pull/2
https://github.com/android-ia/device-androidia-mixins/pull/31
https://github.com/android-ia/device-androidia/pull/39

**Comment by xiaopingx** [comment]
https://github.com/android-ia/device-intel-common/pull/2
https://github.com/android-ia/system-core/pull/3
https://github.com/android-ia/bootable-recovery/pull/2
https://github.com/android-ia/device-androidia-mixins/pull/31
https://github.com/android-ia/device-androidia/pull/39

**Comment by xiaopingx** [comment]
https://github.com/android-ia/device-intel-common/pull/2
               https://github.com/android-ia/system-core/pull/3
               https://github.com/android-ia/bootable-recovery/pull/2
               https://github.com/android-ia/device-androidia-mixins/pull/31
               https://github.com/android-ia/device-androidia/pull/39

**Comment by xiaopingx** [comment]
https://github.com/android-ia/device-intel-common/pull/2 
https://github.com/android-ia/system-core/pull/3
https://github.com/android-ia/bootable-recovery/pull/2
https://github.com/android-ia/device-androidia-mixins/pull/31 
https://github.com/android-ia/device-androidia/pull/39

**Comment by kalyankondapally** [comment]
@xiaopingx can u address the review comments  ?

**Pull request closed without merging**
