### PR TITLE
Increase number of serial ports to 8.

### PR DESCRIPTION
**Pull request by goffioul**
Jira: None
Test: There are 8 serial devices (/dev/ttyS[0-7]) after boot

Signed-off-by: Michael Goffioul <michael.goffioul@gmail.com>

### CODE REVIEW

**Comment by kalyankondapally** [comment]
@shobhitka @harishkrupo u guyz have been working on this a lot, can u help review this

**Comment by kalyankondapally** [comment]
@Kishore409 ping

**Comment by kalyankondapally** [comment]
merged thx

**Comment by goffioul** [comment]
I see the commit has been reverted. So what's next?

**Comment by kalyankondapally** [comment]
@Kishore409 is analyzing the issue on joul and see what is the no we can have here. Looks like we probably need to start working on having custom defconfig files which will be automerged during build :)

**Pull request closed without merging**
