### PR TITLE
Add Selinux policy for hwc.info service

### PR DESCRIPTION
**Pull request by pyn1**
Jira : None
Test : Permission denied message is not seen.

Signed-off-by: Poornima <poornima.y.n@intel.com>

### CODE REVIEW

**Comment by android-ia-srv** [comment]
Commit message is invalid for commit id: https://github.com/android-ia/device-androidia/pull/116/commits/f41c12dab63e5dfdcee195e25c4984c088c746ec <br>Commit message should be as below: <br><br>Jira: Link to Jira [Default:None.]<br>Test: What tests are expected to pass <br>Signed-off-by: <Author/Contributor><br><br>For more details please refer to below wiki link: https://github.com/android-ia/manifest/wiki/Contributions

**Comment by pyn1** [comment]
@kalyankondapally  @sgnanase , please review.

**Comment by kalyankondapally** [comment]
lgtm

**Comment by pyn1** [comment]
@sgnanase,  Can you please review and merge it. As this is critical to solve UI restart issue on Android IA 2.0.
Thanks

**Pull request merged**
